/* Generated by Cython 3.0.0a10 */

#ifndef __PYX_HAVE__raymarchingC2
#define __PYX_HAVE__raymarchingC2

#include "Python.h"

#ifndef __PYX_HAVE_API__raymarchingC2

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C struct __pyx_obj_13raymarchingC2_Rules *rules;

#endif /* !__PYX_HAVE_API__raymarchingC2 */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initraymarchingC2(void);
#else
/* WARNING: Use PyImport_AppendInittab("raymarchingC2", PyInit_raymarchingC2) instead of calling PyInit_raymarchingC2 directly from Python 3.5 */
PyMODINIT_FUNC PyInit_raymarchingC2(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"raymarchingC2\", PyInit_raymarchingC2) instead of calling PyInit_raymarchingC2 directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"raymarchingC2\", PyInit_raymarchingC2) instead of calling PyInit_raymarchingC2 directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"raymarchingC2\", PyInit_raymarchingC2) instead of calling PyInit_raymarchingC2 directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_raymarchingC2_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_raymarchingC2() __PYX_WARN_IF_PyInit_raymarchingC2_INIT_CALLED(PyInit_raymarchingC2())
#endif
#endif

#endif /* !__PYX_HAVE__raymarchingC2 */
